services:
  postgres:
    image: postgres:18-alpine
    container_name: portal-mensagens-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: portal_mensagens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5434:5432"
    volumes:
      - portal_mensagens_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portal_mensagens"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  portal_mensagens_data: